In [9]:
import pandas, sys
import pandas as pd


a = pd.read_csv("cat_adopted_2020.csv")
b = pd.read_csv("dog_adopted_2020.csv")

In [10]:
c=pd.concat([a,b])

In [11]:
c.shape

(36197, 26)

In [12]:
c.head()

,id,organization_id,type,age,gender,size,coat,organization_animal_id,status,published_at,...,colors_primary,colors_secondary,attributes_spayed_neutered,attributes_house_trained,attributes_declawed,attributes_special_needs,attributes_shots_current,environment_children,environment_dogs,environment_cats
0,50167537,MD307,Cat,Baby,Female,Medium,Short,missing,adopted,2020-12-30T23:59:45+0000,...,Dilute Tortoiseshell,missing,True,True,False,False,True,True,True,True
1,50167559,NV129,Cat,Baby,Female,Medium,Short,dec20,adopted,2020-12-30T23:58:53+0000,...,Buff / Tan / Fawn,missing,True,True,False,False,True,missing,True,True
2,50167410,CT40,Cat,Baby,Female,Medium,Short,missing,adopted,2020-12-30T23:56:30+0000,...,Black,missing,True,True,False,False,True,missing,missing,True
3,50167494,NY1063,Cat,Young,Female,Medium,Short,missing,adopted,2020-12-30T23:55:50+0000,...,Gray & White,missing,False,True,False,False,False,missing,missing,missing
4,50147331,WI394,Cat,Adult,Male,Large,Short,missing,adopted,2020-12-30T23:52:52+0000,...,White,missing,True,True,False,False,True,missing,missing,True

In [13]:
c.to_csv('catdog_adopted_2020.csv')